---
title: "Differential Expression on Mif NaCl Experiment"
author: "Micah Gearhart"
date: "7/3/2016"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries
```{r libraries,eval=T,results='hide',message=FALSE,warning=FALSE}
library(Rsamtools)
library(GenomicAlignments)
library(BiocParallel)
library(DESeq2)
library(ggplot2)
library(magrittr)
library(biomaRt)
library(ChIPpeakAnno)

ts<-format(Sys.time(), "%a_%b_%d_%Y_%H%M")
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```


## Get annotation data from biomaRt
```{r biomaRt,eval=F}
ensembl_84<-useMart(biomart="ENSEMBL_MART_ENSEMBL",host = "useast.ensembl.org", dataset="mmusculus_gene_ensembl")
txdb84<-makeTxDbFromBiomart(biomart="ENSEMBL_MART_ENSEMBL",host = "www.ensembl.org",dataset="mmusculus_gene_ensembl")
ens84<-exonsBy(txdb84,by="gene")
mgi <-  getBM(attributes = c("ensembl_gene_id", "mgi_id", "mgi_symbol"), filters = "ensembl_gene_id",
    values = names(ens84), mart = ensembl_84)
save(ens84,file="ens84_mouse.rdata")
save(mgi,file="mgi.rdata")
```

## EDA
```{r}
load("igarash0_Project_004_genehits_ens84Thu_Jun_30_2016_2351.rdata")
load("mgi.rdata")
cds <- DESeqDataSet(genehits,design=~1)
cds$filename<-rownames(colData(cds))
colData(cds)$genotype<-as.factor(sapply(strsplit(rownames(colData(cds)),"-"),function(x){x[1]}))
colData(cds)$salt<-factor(ifelse(sapply(strsplit(rownames(colData(cds)),"-"),function(x){x[2]})=="Nacl","Nacl","noSalt"),levels=c("noSalt","Nacl"))
plotPCA(DESeqTransform(cds),intgroup=c("salt","genotype"))+
  scale_color_manual(values=cbPalette)  + theme_bw()
```

```{r}
design(cds)<- ~ genotype + salt + genotype:salt
cds <- DESeq(cds)

plotCounts(cds,"ENSMUSG00000020679",intgroup=c("salt","genotype"),returnData=F)
```

```{r}
gg_plotCounts<-function(x="ENSMUSG00000020679") {
  if (substr(x,1,7)=="ENSMUSG") {
  title<-mgi[grep(x,mgi$ensembl_gene_id),"mgi_symbol"]
  } else {
    title<-x
    x<-mgi[grep(paste0("^",title,"$"),mgi$mgi_symbol),"ensembl_gene_id"]
  }
  
plotCounts(cds,x,intgroup=c("salt","genotype"),returnData=T) %>% 
  ggplot(aes(x=salt, y=count)) +
  geom_point(position=position_jitter(w=0.1,h=0)) + ggtitle(paste0(x,":",title)) +
 # scale_y_log10(breaks=c(25,100,400)) + 
 # scale_y_continuous(trans="log2") + ylim(0,25000) +
  expand_limits(x=0, y = 0) +
  facet_grid(~genotype) + theme_bw()
  }

gg_plotCounts("Nr1h4")
```

## Look for genes with High Interaction Term
```{r}
resultsNames(cds)
res<-results(cds, name="genotypeMif.saltNacl")
summary(res)
resDF<-as.data.frame(res)
resDF<-resDF[!is.na(resDF$padj),]
resDF<-resDF[with(resDF,order(-log2FoldChange)),]
idx<-match(rownames(resDF),mgi$ensembl_gene_id)
resDF$mgi<-mgi[idx,"mgi_symbol"]
head(resDF)
gg_plotCounts("Slc14a1")
gg_plotCounts("Lrrn3")
tail(resDF)
gg_plotCounts("Saa3")
gg_plotCounts("Zfp750")

resDF<-resDF[with(resDF,order(padj)),]
head(resDF)
gg_plotCounts("Ppbp")

gg_plotCounts("Nr1h4")
gg_plotCounts("Pkhd1")

```

## control logfc vs hnf1b logfc
```{r}
cds2<-cds
cds2$group <- factor(paste0(cds2$genotype, cds2$salt))
design(cds2)<- ~ group
cds2 <- DESeq(cds2) 
resultsNames(cds2)

summary(res_wt<-results(cds2, contrast=c("group","ControlnoSalt","ControlNacl"),alpha=0.05))
res_wt<-as.data.frame(res_wt)
colnames(res_wt)<-paste0("WT",".",colnames(res_wt))

summary(res_hnf1b<-results(cds2, contrast=c("group","MifnoSalt","MifNacl")))
res_hnf1b<-as.data.frame(res_hnf1b)
colnames(res_hnf1b)<-paste0("hnf1b",".",colnames(res_hnf1b))

res_merged<-cbind(res_wt,res_hnf1b)
head(res_merged)
res_merged<-res_merged[res_merged$WT.padj < 0.05 & res_merged$WT.baseMean > 100,]
dim(res_merged)
head(res_merged)
res_merged<-subset(res_merged,!(is.na(WT.log2FoldChange) | is.na(hnf1b.log2FoldChange)))
idx<-match(rownames(res_merged),mgi$ensembl_gene_id)
res_merged$mgi<-mgi[idx,"mgi_symbol"]
res_merged$'Effect Size'<-abs(res_merged$WT.log2FoldChange-res_merged$hnf1b.log2FoldChange)

plot(res_merged$WT.log2FoldChange,res_merged$hnf1b.log2FoldChange,pch=16,cex=0.5,xlab="WT Salt Induced Log2FC",ylab="Hnf1b Salt Induced Log2FC",col=ifelse(res_merged$`Effect Size` > 1,"red","black"))
abline(h=0,col="red2")
#res_merged[identify(res_merged$WT.log2FoldChange,res_merged$hnf1b.log2FoldChange,labels=res_merged$mgi),]
```

## load Karam's Direct Target List
```{r}
head(dt<-read.table("hnf1b_direct_targets.txt",stringsAsFactors=F))
dt<-AnnotationDbi::select(org.Mm.eg.db,columns="ENSEMBL",keytype="ALIAS",keys=dt$V1)
sum(!is.na(dt$ENSEMBL))
res_merged$'Direct Target'<-rownames(res_merged) %in% dt$ENSEMBL
View(res_merged)

plot(res_merged$WT.log2FoldChange,res_merged$hnf1b.log2FoldChange,pch=16,cex=0.5,xlab="WT Salt Induced Log2FC",ylab="Hnf1b Salt Induced Log2FC",col=ifelse(res_merged$`Direct Target`,"red","black"))

res_merged<-res_merged[with(res_merged,order('Direct Target','Effect Size')),]
View(res_merged)
res_merged[res_merged$`Direct Target` & res_merged$`Effect Size` > 1,]

gg_plotCounts("Arhgap24")
gg_plotCounts("Col4a1")
```

```{bash MACS,eval=F}
macs2 callpeak --call-summits -c igg_rep1_SRR2124926.dedup.unique.bam  -t hnf1b_rep1_SRR2124924.dedup.unique.bam -n hnf1b_rep1 -g mm
macs2 callpeak --call-summits -c igg_rep2_SRR2124927.dedup.unique.bam  -t hnf1b_rep2_SRR2124925.dedup.unique.bam -n hnf1b_rep2 -g mm
```

##
```{r}
narrowPeakToGRanges<-function(file) {
  x <- read.table(file,stringsAsFactors=F)
  gr <-GRanges(seqnames=x$V1, ranges = IRanges(start=x$V2, end=x$V3),
               strand="*", score=x$V5, e=x$V7,summit=x$V10)
  return(gr)
}

#devtools::install_github("lawremi/HelloRanges")
hnf1b_rep1<-narrowPeakToGRanges("hnf1b_rep1_peaks.narrowPeak")
hnf1b_rep2<-narrowPeakToGRanges("hnf1b_rep2_peaks.narrowPeak")
pairs<-findOverlapPairs(hnf1b_rep1,hnf1b_rep2)
hnf1b<-pintersect(pairs)
head(hnf1b_rep2)

tss<-getAnnotation(ensembl_84,featureType="TSS")
tss<-tss[rownames(res[res$baseMean > 1,])]
hnf1b_anno <- annotatePeakInBatch(hnf1b, AnnotationData=tss, output="both", maxgap=100L)
summary(hnf1b_anno$shortestDistance)
table(hnf1b_anno$insideFeature)
p1<-hnf1b_anno[hnf1b_anno$insideFeature=="upstream" & hnf1b_anno$shortestDistance < 50000,]$feature
p2<-hnf1b_anno[hnf1b_anno$insideFeature=="inside" | hnf1b_anno$insideFeature=="overlapStart" | hnf1b_anno$insideFeature=="overlapEnd"]$feature
p<-unique(c(p1,p2))
res_merged$`Nearby Peak`<-rownames(res_merged) %in% p
sum(res_merged$`Nearby Peak`)
View(res_merged)
```

## Create Output
```{r}
colnames(res_merged)
temp<-res_merged[,c("mgi","WT.baseMean","WT.log2FoldChange","WT.padj","hnf1b.log2FoldChange","hnf1b.padj","Effect Size","Direct Target","Nearby Peak")]
colnames(temp)<-c("MGI Symbol","baseMean","WT.log2FoldChange","WT.padj","Hnf1b.log2FoldChange","Hnf1b.padj","Effect_Size","Direct_Target","Nearby Peak")
temp<-temp[with(temp,order(-Effect_Size)),]
head(temp,40)
write.csv(temp,file="hnf1b_nacl_log2FCs_wChIPdata_071016.csv",quote=F)
options(httr_oob_default=TRUE)
gs_auth(new_user = TRUE)
googlesheets::gs_upload("hnf1b_nacl_log2FCs_wChIPdata_071016.csv")
```

