#!/bin/bash -l
file_R1=$1
file_R2="${file_R1/R1/R2}"
base_R1=$( basename "$file_R1" )
base_R2="${base_R1/R1/R2}"
j="${base_R1%%.*}"
i="${j/_R1_001/}"
#gzip -c $file > $i.gz
#echo $file_R1
#echo $base_R1
#echo $i

java -Xmx16g -jar /home/bardwell/shared/Trimmomatic-0.32/trimmomatic-0.32.jar PE \
-threads 2 -phred33 \
$file_R1 $file_R2 \
fastq/$i.R1_trimmed.fastq.gz fastq/$i.UR1_trimmed.fastq.gz \
fastq/$i.R2_trimmed.fastq.gz fastq/$i.UR2_trimmed.fastq.gz \
ILLUMINACLIP:/home/bardwell/shared/Trimmomatic-0.32/adapters/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:5 MINLEN:25


#sort the bam file
#samtools sort $j $i.bowtie
#create the index file
#samtools index $i.bowtie.bam

#bedtools genomecov -bg -ibam $i.bowtie.bam > $i.bowtie.bedGraph


#/home/bardwell/shared/bedGraphToBigWig $i.bowtie.bedGraph \
#/panfs/roc/rissdb/genomes/Mus_musculus/GRCm38_canon/seq/GRCm38_canon.len \
#$i.bowtie.bigWig

